sonar.projectKey=portfolio
sonar.organization=lowriwyllt
sonar.sources=app
sonar.tests=app/__tests__,app/components/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.module.css,**/*.test.ts,**/*.test.tsx,**/fonts.ts