sonar.projectKey=lowriwyllt_portfolio
sonar.organization=lowriwyllt
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=src/**/__tests__/**/*.ts,src/**/__tests__/**/*.tsx,src/**/__tests__/**/*.js,src/**/__tests__/**/*.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info