sonar.projectKey=lowriwyllt_portfolio
sonar.organization=lowriwyllt
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=app/**/__tests__/**/*.ts,app/**/__tests__/**/*.tsx,app/**/__tests__/**/*.js,app/**/__tests__/**/*.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info